service: derpiview
provider:
  credentials: ${secrets:lgs-aws}
  name: aws
  runtime: nodejs8.10

tenant: jeremy
app: lgs

plugins:
  - '@serverless/enterprise-plugin'

functions:
  getFile:
    handler: handler.hello
    events:
      - http:
          path: /post/{postId}/representations/{size}
          method: GET
